name: node integration and unit tests

on:
  push:
    branches: main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - run: |
          cd backend
          npm ci

      - run: |
          cd frontend
          npm ci
      - run: |
          cd backend
          npm test
